name: Build and test
on: push
jobs:
   gfortran:
      runs-on: ubuntu-latest
      steps:
      - name: Clone FABM VIMS repository
        uses: actions/checkout@v2
        with:
           path: fabm-vims
      - name: Clone FABM
        uses: actions/checkout@v2
        with:
           path: fabm
           repository: fabm-model/fabm
      - name: Build
        run: |
          mkdir $GITHUB_WORKSPACE/build
          cd $GITHUB_WORKSPACE/build
          cmake $GITHUB_WORKSPACE/fabm -DFABM_HOST=schism  -DFABM_INSTITUTES=vims -DFABM_VIMS_BASE=$GITHUB_WORKSPACE/fabm-vims
          make
